extends SceneTree
func _init() -> void:
	call_deferred("_run")
func _run() -> void:
	var data: BuildingData = load("res://.godot/building_editor_house.tres")
	var original_cost: Dictionary = load("res://data/buildings/HouseData.tres").construction_cost.duplicate()
	assert(data.construction_time == 19 and data.construction_cost[&"wood"] == 55)
	var main: Node3D = load("res://Scene/main.tscn").instantiate()
	main.level_preset = main.level_preset.duplicate(true)
	main.level_preset.layout_seed = 418
	main.level_preset.events.clear()
	main.level_preset.camp_config.enabled = false
	root.add_child(main)
	current_scene = main
	for index in range(20):
		await physics_frame
		await process_frame
	var base: Node3D = get_first_node_in_group("bases")
	var house: House = data.building_scene.instantiate()
	house.set_building_data(data)
	main.add_child(house)
	house.global_position = base.global_position + Vector3(5, 0, 5)
	var ghost: BuildingGhost = main.get_node("Systems/BuildingGhost")
	ghost.select_building(data)
	assert(ghost.preview_model_bounds.size.is_equal_approx(Vector3.ONE))
	ghost.cancel_preview()
	var site: ConstructionSite = load("res://Scene/building/construction_site.tscn").instantiate()
	site.setup(data, Vector2i.ZERO, 0, false)
	site.set_activation_deferred_until_unpause(true)
	main.add_child(site)
	assert(site.model_instance == null and site.get_node_or_null("ResourceStorage") == null)
	assert(site.model_bounds.size.is_equal_approx(Vector3.ONE))
	site.queue_free()
	var population: PopulationManager = get_first_node_in_group("population_manager")
	population.refresh_population()
	assert(base.get_max_health() == 1000.0 and base.armor == 1.0)
	var health: float = base.get_health()
	assert(base.take_damage(10.0) == 9.0 and base.get_health() == health - 9.0)
	assert(house.get_max_health() == 450.0 and house.model_instance != null)
	assert(house.take_damage(10.0) == 9.0 and house.get_health() == 441.0)
	assert(house.take_damage(0.0) == 0.0 and house.take_damage(0.5) == 1.0)
	var storage: ResourceStorage = house.get_node("ResourceStorage")
	assert(storage.add(&"meat", 12.0) == 10.0 and storage.add(&"wood", 1.0) == 0.0)
	assert(storage.get_capacity(&"meat") == 10.0)
	assert(house.get_node("ClickArea") != null)
	assert(house.get_housing_capacity() == 7 and population.get_housing_capacity() == 12)
	assert(house.get_building_data().construction_cost[&"wood"] == 55)
	assert(load("res://data/buildings/HouseData.tres").construction_cost == original_cost)
	var lumber_data: BuildingData = load("res://data/buildings/LumberCampData.tres")
	var lumber: Node3D = lumber_data.building_scene.instantiate()
	lumber.set_building_data(lumber_data)
	main.add_child(lumber)
	assert(lumber.get_health() == 300.0 and lumber.take_damage(10.0) == 9.0)
	assert(lumber.get_node("ResourceStorage").get_capacity(&"wood") == 20.0)
	var army_data: BuildingData = load("res://data/buildings/BarracksData.tres")
	var army: Barracks = army_data.building_scene.instantiate()
	army.set_building_data(army_data)
	main.add_child(army)
	army.set_process(false)
	assert(army.add_food(&"meat", 50.0) == 30.0 and army.add_food(&"grain", 1.0) == 0.0)
	var unit: Node = get_nodes_in_group("villagers")[0]
	unit.set_combat_role(CombatRole.Type.SWORDSMAN)
	army.garrisoned_units.append(unit)
	unit.enter_garrison(army)
	assert(not unit.visible)
	base.storage.set_capacity(&"meat", 100.0)
	base.storage.add(&"meat", 20.0)
	army.food_inventory.clear()
	army.building_data = army_data.duplicate(true)
	army.building_data.storage_capacities = {&"meat": 3.0}
	assert(unit.choose_food(base.storage, army) == &"meat")
	assert(army.add_food(&"grain", 1.0) == 0.0 and army.add_food(&"meat", 10.0) == 3.0)
	assert(unit.choose_food(base.storage, army).is_empty())
	army.take_damage(1000.0)
	assert(unit.visible and unit.garrisoned_in == null)
	main.queue_free()
	await process_frame
	print("建筑编辑器运行测试通过：血量护甲、模型替换保留住房与碰撞、肉类容量10、军粮容量、军营死亡释放驻军")
	quit()
