extends SceneTree

var failed: bool = false

func _initialize() -> void:
	call_deferred("_run")

func _expect(ok: bool, message: String) -> void:
	print("[通过] " if ok else "[失败] ", message)
	failed = failed or not ok

func _run() -> void:
	var fog = load("res://Script/world/fog_of_war.gd").new()
	root.add_child(fog)
	fog.set_process(false)
	fog.initialized = true
	fog.extent = Vector2(80, 64)
	fog.visibility_map = Image.create(256, 256, false, Image.FORMAT_L8)
	fog.visibility_map.fill(Color.WHITE)
	node_added.connect(fog._on_node_added)
	node_removed.connect(fog._on_node_removed)
	var resource := Node3D.new()
	resource.add_to_group("resources")
	var mesh := MeshInstance3D.new()
	var collider := Area3D.new()
	resource.add_child(mesh)
	resource.add_child(collider)
	root.add_child(resource)
	fog._refresh_object_visibility()
	_expect(mesh.visible and collider.input_ray_pickable, "可见资源可以显示并点击")
	var unrelated := Node3D.new()
	root.add_child(unrelated)
	_expect(fog.visibility_children.has(resource) and fog.visibility_children[resource].has("last_visible"), "无关特效新增保留资源显隐缓存")
	unrelated.free()
	_expect(fog.visibility_children.has(resource), "无关特效删除不失效资源缓存")
	fog.visibility_map.fill(Color.BLACK)
	fog._refresh_object_visibility()
	_expect(not mesh.visible and not collider.input_ray_pickable and resource.get_meta("fog_hidden"), "视野消失仍更新显示和拾取")
	fog.visibility_map.fill(Color.WHITE)
	fog._refresh_object_visibility()
	_expect(mesh.visible and collider.input_ray_pickable, "恢复视野后恢复显示和拾取")
	var replacement := MeshInstance3D.new()
	resource.add_child(replacement)
	_expect(not fog.visibility_children.has(resource), "对象内部新增网格仅失效该对象缓存")
	fog._refresh_object_visibility()
	resource.remove_child(mesh)
	mesh.free()
	_expect(not fog.visibility_children.has(resource), "对象内部删除网格立即清除旧引用")
	fog._refresh_object_visibility()
	_expect(fog.visibility_children[resource].meshes.size() == 1, "删除后重新收集有效网格")
	var building := Node3D.new()
	building.add_to_group("buildings")
	var warning := MeshInstance3D.new()
	warning.set_meta("fog_visible", false)
	building.add_child(warning)
	root.add_child(building)
	fog._refresh_object_visibility()
	_expect(not warning.visible, "建筑提醒保持自己的隐藏状态")
	warning.set_meta("fog_visible", true)
	fog._refresh_object_visibility()
	_expect(warning.visible, "建筑提醒状态变化不被静态资源缓存吞掉")
	building.free()
	resource.free()
	_expect(fog.visibility_children.is_empty(), "对象删除后没有遗留缓存引用")
	fog.free()
	quit(1 if failed else 0)
